# cmd conda build .
package:
    name: onedmin
    version: "1.0.0"

source:
    path: .

requirements:
    build:
        - cmake
        - {{ compiler('fortran') }}
        - blas
        - openblas # [linux]
    run:
        - cmake
        - {{ compiler('fortran') }}
        - blas
        - openblas # [linux]
