version: 2
jobs:
    build-and-test:
        docker:
            - image: continuumio/miniconda3
        steps:
          - checkout
          - run:
              name: Create conda environment
              command: |
                  apt-get update --yes
                  apt-get install --yes build-essential
                  conda env create -f environment.yml
          - run:
              name: Build the code
              command: |
                  source activate onedmin-env
                  bash build.sh
          - run:
              name: Test the code
              command: |
                  source activate onedmin-env
                  cd examples/ch4_he/exp6/SpinMethod1
                  onedmin-exp6.x < input.dat > output.dat
                  cd ../SpinMethod2
                  onedmin-exp6.x < input.dat > output.dat
workflows:
    version: 2
    build-all:
        jobs:
            - build-and-test
